export const GET_RECENTLY_PLAYED_SUCCESS = 'GET_RECENTLY_PLAYED_SUCCESS';
export const GET_RECENTLY_PLAYED_ERROR = 'GET_RECENTLY_PLAYED_ERROR';

export const GET_TOP_ARTISTS_SUCCESS = 'GET_TOP_ARTISTS_SUCCESS';
export const GET_TOP_ARTISTS_ERROR = 'GET_TOP_ARTISTS_ERROR';

export const GET_NEWALBUMS_SUCCESS = 'GET_NEWALBUMS_SUCCESS';
export const GET_NEWALBUMS_ERROR = 'GET_NEWALBUMS_ERROR';

export const GET_FEATUREDPLAYLISTS_SUCCESS = 'GET_FEATUREDPLAYLISTS_SUCCESS';
export const GET_FEATUREDPLAYLISTS_ERROR = 'GET_FEATUREDPLAYLISTS_ERROR';

export const GET_TOP_TRACKS_SUCCESS = 'GET_TOP_TRACKS_SUCCESS';
export const GET_TOP_TRACKS_ERROR = 'GET_TOP_TRACKS_ERROR';
