export const SET_TRACK_SUCCESS = 'SET_TRACK_SUCCESS';
export const SET_TRACK_ERROR = 'SET_TRACK_ERROR';

export const PLAY_TRACK_SUCCESS = 'PLAY_TRACK_SUCCESS';
export const PLAY_TRACK_ERROR = 'PLAY_TRACK_ERROR';
